# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
- pre-commit
default_language_version:
  python: python3.8
default_stages:
- commit
- manual
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: check-merge-conflict
  - id: name-tests-test
    args:
    - --pytest-test-first
    exclude: ^tests/(fixtures/|util.py$)
  - id: debug-statements
  - id: detect-private-key
  - id: mixed-line-ending
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/python-poetry/poetry
  rev: 1.2.1    # auto-updates to a wrong version. Should be: 1.2.1
  hooks:
  - id: poetry-check
- repo: https://github.com/frnmst/md-toc
  rev: 8.1.4
  hooks:
  - id: md-toc
    args: [--in-place, --skip-lines=10, --newline-string=\n, github]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --indent=2
  - id: pretty-format-ini
    args:
    - --autofix
- repo: https://github.com/asottile/pyupgrade
  rev: v3.1.0
  hooks:
  - id: pyupgrade
    args:
    - --py37-plus
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.8.4
  hooks:
  - id: reorder-python-imports
    args:
    - --py37-plus
    - --add-import=from __future__ import annotations
- repo: https://github.com/PyCQA/autoflake
  rev: v1.7.4
  hooks:
  - id: autoflake
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black
    exclude: ^.github/
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-check-blanket-noqa
  - id: text-unicode-replacement-char
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-blind-except
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-rst-docstrings
    - flake8-implicit-str-concat
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.982
  hooks:
  - id: mypy
    additional_dependencies: [types-setuptools, types-toml]
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
